[package]
name = "home-dir"
version = "0.1.0"
authors = ["eulegang <eulegang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

nix = "0.18"
